#Ejercicio_Protocolo_Validación

Haga una red neuronal de 2 capas (2 neuronas ocultas y 1 de salida) usando únicamente numpy para ajustar el XOR usando la función escalera como función de activación. Tip: XOR=AND(OR,NAND)

In [ ]:
import numpy as np

In [ ]:
Al=[0]*2
Bl=[0]*2
Bl

[0, 0]

In [ ]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
Al[0]=np.array([[1/2,-1/3],[1/2,-1/3]])
Bl[0]=np.array([-1/2,1/2])
Al[1]=np.array([[1/3],[1/3]])
Bl[1]=np.array([-1/2])
Bl[1]

array([-0.5])

In [ ]:
step=lambda x:(x>=0)

In [ ]:
Xl=[]
x=X
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
for L in range(2):
  x=step(np.dot(x,Al[L])+Bl[L])
  Xl.append(x)
print(Xl)

[array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True, False]]), array([[False],
       [ True],
       [ True],
       [False]])]
